[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectRoot,

    [string]$OutputPath,

    [int]$TopFiles = 30
)

$ErrorActionPreference = "Stop"

$resolvedProject = Resolve-Path -LiteralPath $ProjectRoot
$projectPath = $resolvedProject.ProviderPath

$excludedDirs = @(
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".turbo",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".cache"
)

$sourceExtensions = @(
    ".rs", ".js", ".jsx", ".ts", ".tsx", ".py", ".go", ".java", ".kt", ".cs",
    ".cpp", ".c", ".h", ".hpp", ".swift", ".php", ".rb", ".vue", ".svelte"
)

function Get-TopologyRelativePath {
    param([Parameter(Mandatory = $true)][string]$FullName)

    if ($FullName.StartsWith($projectPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $FullName.Substring($projectPath.Length).TrimStart([char[]]@("\", "/"))
    }

    return $FullName
}

function Test-IsExcludedPath {
    param([Parameter(Mandatory = $true)][string]$FullName)

    $relative = Get-TopologyRelativePath -FullName $FullName
    foreach ($dir in $excludedDirs) {
        if ($relative -eq $dir -or $relative.StartsWith("$dir\")) {
            return $true
        }
    }
    return $false
}

$topDirs = Get-ChildItem -LiteralPath $projectPath -Directory -Force |
    Where-Object { $excludedDirs -notcontains $_.Name } |
    Sort-Object Name |
    Select-Object -ExpandProperty Name

$files = Get-ChildItem -LiteralPath $projectPath -Recurse -File -Force |
    Where-Object { -not (Test-IsExcludedPath -FullName $_.FullName) }

$sourceFiles = $files |
    Where-Object { $sourceExtensions -contains $_.Extension.ToLowerInvariant() }

$largest = $sourceFiles |
    Sort-Object Length -Descending |
    Select-Object -First $TopFiles

$governanceHints = $files |
    Where-Object {
        $_.Name -match "README|POLICY|GOVERNANCE|TREE|MATRIX|CLOSEOUT|ARCHITECTURE|ROADMAP" -or
        $_.FullName -match "governance|docs|markdown"
    } |
    Select-Object -First 80

$entryHints = $files |
    Where-Object {
        $_.Name -match "main\..+|lib\..+|index\..+|app\..+|server\..+|routes?\..+|api\..+|mod\.rs|Cargo\.toml|package\.json|pyproject\.toml"
    } |
    Select-Object -First 80

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Topology Inventory Draft") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("> Generated by topological-modular-governance inventory. Treat this as a read-only draft, not final architecture.") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("## Top-Level Directories") | Out-Null
$lines.Add("") | Out-Null
foreach ($dir in $topDirs) {
    $lines.Add(('- `{0}`' -f $dir)) | Out-Null
}
$lines.Add("") | Out-Null
$lines.Add("## Source File Summary") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("- source_files: $($sourceFiles.Count)") | Out-Null
$lines.Add("- all_scanned_files: $($files.Count)") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("## Largest Source Files") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("| Path | KB |") | Out-Null
$lines.Add("| --- | ---: |") | Out-Null
foreach ($file in $largest) {
    $relative = Get-TopologyRelativePath -FullName $file.FullName
    $kb = [math]::Round($file.Length / 1kb, 1)
    $lines.Add(('| `{0}` | {1} |' -f $relative, $kb)) | Out-Null
}
$lines.Add("") | Out-Null
$lines.Add("## Candidate Entrypoints") | Out-Null
$lines.Add("") | Out-Null
foreach ($file in $entryHints) {
    $relative = Get-TopologyRelativePath -FullName $file.FullName
    $lines.Add(('- `{0}`' -f $relative)) | Out-Null
}
$lines.Add("") | Out-Null
$lines.Add("## Governance And Docs Hints") | Out-Null
$lines.Add("") | Out-Null
foreach ($file in $governanceHints) {
    $relative = Get-TopologyRelativePath -FullName $file.FullName
    $lines.Add(('- `{0}`' -f $relative)) | Out-Null
}
$lines.Add("") | Out-Null
$lines.Add("## Suggested First Topology Questions") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("1. Which top-level directories are real parent modules?") | Out-Null
$lines.Add("2. Which largest files are parent facades, and which are mixed-responsibility files?") | Out-Null
$lines.Add("3. Where are public APIs, routes, schemas, events, commands, or UI surfaces?") | Out-Null
$lines.Add("4. Which modules own state, locks, persistence, auth, external IO, or release paths?") | Out-Null
$lines.Add("5. Which docs are hot assets, and which are cold background references?") | Out-Null

$text = $lines -join [Environment]::NewLine

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Write-Output $text
} else {
    $resolvedOutput = $OutputPath
    if (-not [System.IO.Path]::IsPathRooted($resolvedOutput)) {
        $resolvedOutput = Join-Path $projectPath $OutputPath
    }
    $outputDir = Split-Path -Parent $resolvedOutput
    if (-not [string]::IsNullOrWhiteSpace($outputDir)) {
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
    }
    Set-Content -Encoding UTF8 -LiteralPath $resolvedOutput -Value $text
    Write-Host "Topology inventory draft written: $resolvedOutput"
}
